   



#replicaSet
#A ReplicaSet ensure that a specific number of identical pds are always running.  It monitors pods and start new ones if any are terminated.

#write the replicaset yaml code
apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: dotnetapp-replicaset
  labels:
    app: dotnetapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - name: dotnetapp
          image: iwaydevpos/dotnetapp
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: mysecret1 